countries = {
    "ad":  "Andorra",
    "au":  "Australia",
    "ar":  "Argentina",
    "bd":  "Bangladesh",
    "be":  "Belgium",
    "bt":  "Bhutan",
    "bw":  "Botswana",
    "br":  "Brazil",
    "bg":  "Bulgaria",
    "kh":  "Cambodia",
    "ca":  "Canada",
    "cl":  "Chile",
    "hr":  "Croatia",
    "co":  "Colombia",
    "cz":  "Czech Republic",
    "dk":  "Denmark",
    "ee":  "Estonia",
    "fi":  "Finland",
    "fr":  "France",
    "de":  "Germany",
    "gr":  "Greece",
    "hu":  "Hungary",
    "hk":  "Hong Kong",
    "is":  "Iceland",
    "id":  "Indonesia",
    "ie":  "Ireland",
    "it":  "Italy",
    "il":  "Israel",
    "jp":  "Japan",
    "lv":  "Latvia",
    "lt":  "Lithuania",
    "my":  "Malaysia",
    "mx":  "Mexico",
    "nl":  "Netherlands",
    "nz":  "New Zealand",
    "no":  "Norway",
    "pe":  "Peru",
    "pl":  "Poland",
    "pt":  "Portugal",
    "ro":  "Romania",
    "ru":  "Russia",
    "sg":  "Singapore",
    "sk":  "Slovakia",
    "si":  "Slovenia",
    "za":  "South Africa",
    "kr":  "South Korea",
    "es":  "Spain",
    "sz":  "Swaziland",
    "se":  "Sweden",
    "ch":  "Switzerland",
    "tw":  "Taiwan",
    "th":  "Thailand",
    "ua":  "Ukraine",
    "gb":  "United Kingdom",
    "us":  "United States",
}
